name: compgenomr
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base=4.0
  - r-randomforest
  - r-BiocManager
  - bioconductor-rtracklayer
  - r-mass
  - r-devtools
  - r-stringr
  - bioconductor-rhtslib
  - bioconductor-methylkit
  - r-cowplot
  - bioconductor-gviz
  - bioconductor-genomation
  - bioconductor-ggbio
